namespace LLMClient;

public class AsmGrammarNames
{
    private static string[] asmGrammars = new string[]
    {
        "Asciidoc",
        "Bat",
        "Clojure",
        "CoffeeScript",
        "Cpp",
        "CSharp",
        "CSS",
        "Dart",
        "Diff",
        "Docker",
        "FSharp",
        "Git",
        "Go",
        "Groovy",
        "HandleBars",
        "HLSL",
        "HTML",
        "Ini",
        "Java",
        "Javascript",
        "Json",
        "Julia",
        "Latex",
        "Less",
        "Log",
        "Lua",
        "Make",
        "MarkdownBasics",
        "MarkdownMath",
        "ObjectiveC",
        "Pascal",
        "Perl",
        "PHP",
        "PowerShell",
        "Pug",
        "Python",
        "R",
        "Razor",
        "Ruby",
        "Rust",
        "SCSS",
        "ShaderLab",
        "ShellScript",
        "SQL",
        "Swift",
        "TypescriptBasics",
        "Typst",
        "VB",
        "XML",
        "YAML"
    };

    public static IList<string> SupportedGrammars => asmGrammars;
}