#nullable enable

using System.Collections.Generic;

namespace LLMClient.Abstraction;

/// <summary>
/// Describes the final decision made by the host/UI for a file edit proposal.
/// </summary>
public enum FileEditDecisionKind
{
    /// <summary>
    /// Apply the proposed content as-is.
    /// </summary>
    Apply,

    /// <summary>
    /// Reject the proposed edit.
    /// </summary>
    Reject,

    /// <summary>
    /// Cancel the whole interaction flow.
    /// Typically used when the user closes the dialog or explicitly aborts.
    /// </summary>
    Cancel,

    /// <summary>
    /// Apply a modified version of the proposed content.
    /// This is useful when the UI/IDE allows the user to tweak the final content before saving.
    /// </summary>
    ApplyModified
}

/// <summary>
/// Represents the host/UI decision for a file edit proposal.
/// </summary>
public sealed class FileEditDecision
{
    /// <summary>
    /// The selected decision kind.
    /// </summary>
    public required FileEditDecisionKind Decision { get; init; }

    /// <summary>
    /// Optional modified content to apply when <see cref="Decision"/> is
    /// <see cref="FileEditDecisionKind.ApplyModified"/>.
/// </summary>
    public string? ModifiedContent { get; init; }

    /// <summary>
    /// Optional human-readable note from the user or UI.
    /// This can be used for logging, telemetry, or feeding back into the agent loop.
    /// </summary>
    public string? Message { get; init; }

    /// <summary>
    /// Creates an "Apply" decision.
    /// </summary>
    public static FileEditDecision Apply(string? message = null) =>
        new()
        {
            Decision = FileEditDecisionKind.Apply,
            Message = message
        };

    /// <summary>
    /// Creates a "Reject" decision.
    /// </summary>
    public static FileEditDecision Reject(string? message = null) =>
        new()
        {
            Decision = FileEditDecisionKind.Reject,
            Message = message
        };

    /// <summary>
    /// Creates a "Cancel" decision.
    /// </summary>
    public static FileEditDecision Cancel(string? message = null) =>
        new()
        {
            Decision = FileEditDecisionKind.Cancel,
            Message = message
        };

    /// <summary>
    /// Creates an "ApplyModified" decision.
    /// </summary>
    /// <param name="modifiedContent">
    /// The final content that should be written to disk instead of the proposed content.
    /// </param>
    /// <param name="message">Optional human-readable note.</param>
    public static FileEditDecision ApplyModified(string modifiedContent, string? message = null)
    {
        ArgumentNullException.ThrowIfNull(modifiedContent);

        return new FileEditDecision
        {
            Decision = FileEditDecisionKind.ApplyModified,
            ModifiedContent = modifiedContent,
            Message = message
        };
    }
}

/// <summary>
/// Represents a single edit operation proposal in a UI-friendly form.
/// This is intentionally independent from a specific plugin implementation,
/// so the host/UI can inspect the proposed changes at a higher semantic level.
/// </summary>
public sealed class FileEditOperationPreview
{
    /// <summary>
    /// Edit operation type, e.g. replace, delete, insertBefore, insertAfter.
    /// </summary>
    public required string Type { get; init; }

    /// <summary>
    /// Original text used as the anchor or replacement target.
    /// </summary>
    public required string OldText { get; init; }

    /// <summary>
    /// New text to be inserted or used as replacement.
    /// </summary>
    public required string NewText { get; init; }
}

/// <summary>
/// Represents the full preview data for a pending file edit.
/// This is the payload sent from the tool/plugin layer to the host/UI layer.
/// </summary>
public sealed class FileEditPreview
{
    /// <summary>
    /// Original logical path requested by the tool call.
    /// This may be relative or user-facing.
    /// </summary>
    public required string Path { get; init; }

    /// <summary>
    /// Fully resolved absolute path on the local file system.
    /// </summary>
    public required string AbsolutePath { get; init; }

    /// <summary>
    /// Original file content before applying the proposed edit.
    /// </summary>
    public required string OriginalContent { get; init; }

    /// <summary>
    /// Proposed file content after applying the edit in memory.
    /// </summary>
    public required string UpdatedContent { get; init; }

    /// <summary>
    /// Diff text generated by the system for display purposes.
    /// This may be a git-style diff, inline diff, or any text-based patch representation.
    /// </summary>
    public required string DiffText { get; init; }

    /// <summary>
    /// Optional title suitable for UI presentation.
    /// </summary>
    public string? Title { get; init; }

    /// <summary>
    /// Optional subtitle or short description for the UI.
    /// </summary>
    public string? Description { get; init; }

    /// <summary>
    /// Optional collection of parsed edit operations, if available.
    /// Useful for UIs that want to show semantic edit intent in addition to raw diff.
    /// </summary>
    public IReadOnlyList<FileEditOperationPreview>? Operations { get; init; }

    /// <summary>
    /// Optional metadata bag for future extension.
    /// Example uses:
    /// - model name
    /// - tool call id
    /// - conversation id
    /// - agent step number
    /// </summary>
    public IReadOnlyDictionary<string, object?>? Metadata { get; init; }
}

/// <summary>
/// Defines the host/UI interaction contract for reviewing a pending file edit
/// before it is applied to disk.
/// </summary>
/// <remarks>
/// This interface is intended to be implemented by the application/UI layer,
/// not by the plugin itself.
/// 
/// Typical implementations include:
/// - WPF diff dialog
/// - Rider/IDE integration
/// - headless auto-approve implementation
/// - security-focused auto-reject implementation
/// </remarks>
public interface IFileEditInteractionHandler
{
    /// <summary>
    /// Requests the host/UI to review a pending file edit and decide whether it should be applied.
    /// </summary>
    /// <param name="preview">
    /// Full preview information including original content, updated content, and diff text.
    /// </param>
    /// <param name="cancellationToken">
    /// Token used to cancel the interaction.
    /// </param>
    /// <returns>
    /// A <see cref="FileEditDecision"/> describing whether to apply, reject, cancel,
    /// or apply a modified version of the proposed content.
    /// </returns>
    Task<FileEditDecision> ConfirmApplyAsync(
        FileEditPreview preview,
        CancellationToken cancellationToken = default);
}